### PR TITLE
[MINOR] Add log info in stdout

### LINKED ISSUE #165: No scheduler logs when deployed to k8s
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
According to the user guide, it should be possible to see scheduler logs:

```
$ kubectl logs ballista-scheduler-0
[2021-02-19T00:24:01Z INFO  scheduler] Ballista v0.7.0 Scheduler listening on 0.0.0.0:50050
[2021-02-19T00:24:16Z INFO  ballista::scheduler] Received register_executor request for ExecutorMetadata { id: "b5e81711-1c5c-46ec-8522-d8b359793188", host: "10.1.23.149", port: 50051 }
[2021-02-19T00:24:17Z INFO  ballista::scheduler] Received register_executor request for ExecutorMetadata { id: "816e4502-a876-4ed8-b33f-86d243dcf63f", host: "10.1.23.150", port: 50051 }
```

However, I just tried this, and there is no logging.

We should update the user guide to explain how to enable logging or maybe enable it in the provided yaml.

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by Ted-Jiang**
# Which issue does this PR close?

Closes #165 

Currently we can choose print log in
 1. stdout 
 2. create a local file
 
Default , it will print the log in the console (log level will according to `RUST_LOG`),
but if we set `log_dir` param, the log will only save into log file (log level will according to  the setting `log_level_setting`).
 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
It's better to make the writers configurable. If multiple writers, we can separate them by comma. And by default, just set it to be console.

**Comment by avantgardnerio** [comment]
> Default , it will print the log in the console

Excellent, this is definitely what every modern container environment will expect and is in line with the [12 factors](https://12factor.net/logs):

```
It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout
```

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Ted-Jiang

**Comment by Ted-Jiang** [comment]
> LGTM. Thanks @Ted-Jiang

Thanks @andygrove  it`s my bad forgot the stdout😂

**Pull request merged**
