### PR TITLE
Fix nodejs issues in Docker build

### LINKED ISSUE #717: Building Docker images on main branch fails
**Describe the bug**
Docker image build fails with the following error:

```
+ cd ballista/scheduler/ui
[2422](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2423)
+ yarn install
[2423](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2424)
yarn install v1.22.19
[2424](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2425)
[1/4] Resolving packages...
[2425](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2426)
[2/4] Fetching packages...
[2426](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2427)
error sockjs-client@1.6.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
[2427](https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2428)
error Found incompatible module.
```

**To Reproduce**
```
git clone git@github.com:apache/arrow-ballista.git
cd arrow-ballista
./dev/build-ballista-docker.sh
```

**Expected behavior**
Ballista docker images are successfully built. 

**Additional context**
It seems like the node version used by the docker image is no longer supported by the ` sockjs-client@1.6.1`. It seems we'd have two options to solve this:

1. Downgrade ` sockjs-client@1.6.1`
2. Upgrade the base node version used in the build.

Perhaps one option going with 2 is to integrate nvm (Node Version Manager: https://github.com/nvm-sh/nvm#install--update-script) into the docker build, so we can easily update the used node version? I might give this a go if I have time.

### PR DESCRIPTION
**Pull request by jnaous**
Closes #717

Fixes the issue by installing the right version of nodejs.

### CODE REVIEW

**Review by paolorechia — APPROVED** [review]

**Comment by paolorechia** [comment]
LGTM - I didn't test this though :)

**Review by r4ntix — APPROVED** [review]
LGTM

**Comment by kylebrooks-8451** [comment]
Can we merge this? I was hoping to get the docker build to run again.

**Comment by jnaous** [comment]
Waiting for a committer... perhaps @andygrove?

**Comment by r4ntix** [comment]
> @r4ntix Can we merge this? I was hoping to get the docker build to run again.

Sorry, I don't have permission to merge the PR.

@andygrove @yahoNanJing @Ted-Jiang  Could you help review it?

**Review by avantgardnerio — APPROVED** [review]

**Comment by avantgardnerio** [comment]
It looks like it did fix it, and the checks passed in the branch, but it failed when [merged to main](https://github.com/apache/arrow-ballista/actions/runs/5113530837/jobs/9192844132#step:5:23):

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @chakra-ui/icons@1.1.7" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
warning "@chakra-ui/icons > @chakra-ui/icon@2.0.5" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[4/4] Building fresh packages...
Done in 37.20s.
yarn run v1.22.1[9](https://github.com/apache/arrow-ballista/actions/runs/5113530837/jobs/9192844132#step:5:10)
$ react-scripts --openssl-legacy-provider build
/usr/bin/node: bad option: --openssl-legacy-provider
error Command failed with exit code 9.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 9.
```

Does anyone know why that error might be happening there?

**Comment by paolorechia** [comment]
Hi, @avantgardnerio, my first hunch is that the installed node version does not match what we expect (18)

If I’m not mistaken, this OpenSSL flag is added to node 17+

When peeking at the build logs, I saw this (nodejs v12):

https://github.com/apache/arrow-ballista/actions/runs/5113530837/jobs/9192844132#step:4:1079

I hope I read it correctly, hard to search the logs in my mobile phone :)

**Comment by avantgardnerio** [comment]
Hi all, PTAL at https://github.com/apache/arrow-ballista/pull/794 since this seems like it will fix the build.

**Pull request merged**
