### PR TITLE
Executor graceful shutdown: Handle SIGTERM

### LINKED ISSUE #266: Graceful shutdown: Handle `SIGTERM`
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Right now the executors will gracefully shutdown (deregister with the executor) in response to a `SIGINT`:
```
    let (notify_scheduler, stop_reason) = tokio::select! {
        service_val = check_services(&mut service_handlers) => {
            let msg = format!("executor services stopped with reason {:?}", service_val);
            info!("{:?}", msg);
            (true, msg)
        },
        _ = signal::ctrl_c() => {
             // sometimes OS can not log ??
            let msg = "executor received ctrl-c event.".to_string();
             info!("{:?}", msg);
            (true, msg)
        },
        _ = stop_recv.recv() => {
            (false, "".to_string())
        },
    };
```

On kubernetes when a pod terminates it will receive a `SIGTERM` which doesn't appear to be handled so the executor will not gracefully shutdown. 

**Describe the solution you'd like**

Graceful shutdown on unix systems should initiate graceful shutdown on `SIGTERM` 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mingmwang**
# Which issue does this PR close?

Closes #266.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by mingmwang** [comment]
@thinkharderdev

**Comment by mingmwang** [comment]
For windows platform, the latest tokio already supports  "CTRLCLOSE".  I can add it after we upgrade to new tokio version.

**Comment by yahoNanJing** [comment]
LGTM

**Review by thinkharderdev — APPROVED** [review]
LGTM

**Pull request merged**
