### PR TITLE
Remove revive offer event loop

### LINKED ISSUE #136: Remove revive offer event loop
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #136.

 # Rationale for this change

Currently there are two event loop. And the revive offer event loop only works for triggering task scheduling. It's better to combine them into one event loop for easy maintenance. And it's better to refine the encapsulation to provide the only way to change the scheduler state by events and the processing logic in the event loop.

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
@yahoNanJing This now needs a rebase

**Comment by yahoNanJing** [comment]
Thanks @andygrove. Just rebased.

**Comment by andygrove** [comment]
Thanks @yahoNanJing. I will go ahead and merge soon if there are no objections from others.

cc @thinkharderdev @avantgardnerio

**Comment by avantgardnerio** [comment]
I'm sorry, I looked this PR over a couple times, and I just don't understand enough about Ballista (yet) to contribute a meaningful review. 

I suppose I can at least try to explain what I think I understand:

1. it looks like in January we added the ability to push work to executors, rather than having them poll?
2. it looks like the executors know how many CPU resources or memory or whatever, and those are advertised as ReservationOfferings to the scheduler when they connect?
3. and now there's a config setting for whether to push to executors or have them poll, presumably because we will eventually switch over to always push, but we aren't confident enough in that functionality yet?
4. but ebay china has been using the push method on their fork for some time now?
5. because of some simplification in the previous PR, this one was able to eliminate an event loop and associated channel?

I think analyzing these PRs is probably hard because there isn't up-to-date documentation, or documentation in the level of depth of channels, what messages go over them, and who sends and receives them. I will try to piece this together from the code, but it will take me a little while to get up to speed as I'm also having to contribute some things myself.

Hopefully by at least asking these questions I will learn something.

It sounds like @andygrove is willing to merge as long as there is no opposition, and I think that strategy makes sense if this code has been used in production and is just now making its way upstream.

**Comment by yahoNanJing** [comment]
Hi @avantgardnerio, basically both of the pull-based and push-based task scheduling work well in ballista. In general, we should use pull-based task scheduling for RTL purpose and leverage push-based task scheduling for interactive queries for achieving low latency. And since our team mainly uses ballista for interactive queries, our focus and patches will be mainly for the push-based task scheduling.

**Comment by andygrove** [comment]
> I think analyzing these PRs is probably hard because there isn't up-to-date documentation, or documentation in the level of depth of channels, what messages go over them, and who sends and receives them.

I'm in the same boat. I no longer understand how Ballista works. I would like to help with some documentation in my spare time. I started a Google doc that we can collaborate on and then add to the repo.

https://docs.google.com/document/d/1Fd44vVmjSD6NuSGaFjHeI9pFSRxOIWmZ6Rv7aZ3S5Sw/edit?usp=sharing

**Comment by avantgardnerio** [comment]
> The original design doc and discussion is here, https://github.com/apache/arrow-datafusion/issues/1704

@yahoNanJing ty!!! 

@andygrove that looks a lot like what I was hoping for in the developer docs.

**Review by avantgardnerio — APPROVED** [review]
Approving because I now understand the broader context, and at a syntactical level I like this PR.

I don't think I'm qualified yet to speak to things like race conditions, leaks, state convergence, etc so I'll leave that to others like @alamb and @thinkharderdev

**Review by thinkharderdev — APPROVED** [review]
LGTM!

**Pull request merged**
