### PR TITLE
Move ExecutionGraph encoding and decoding logic into execution_graph for better encapsulation

### LINKED ISSUE #149: Better encapsulation for ExecutionGraph
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently the *ExecutionStage* is exposed to the task manager due to the encoding and decoding logic. It's not good to expose it.

**Describe the solution you'd like**

We can move ExecutionGraph encoding and decoding logic into execution_graph for better encapsulation

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #149.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
Hi @andygrove and @thinkharderdev, could you help review this PR?

**Comment by andygrove** [comment]
@thinkharderdev @avantgardnerio @mingmwang any objections to me merging this one?

**Review by thinkharderdev — APPROVED** [review]
LGTM

**Comment by avantgardnerio** [comment]
Sorry I'm late to the party, but :+1:

**Pull request merged**
