### PR TITLE
MINOR: Increase default shuffle.partitions to 16

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

Get better performance with default settings

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Review by avantgardnerio — APPROVED** [review]
IMO 2 is clearly not a good choice for multi-core machines in 2022. 16 sounds much more practice in an age where the lowest core count will likely be 8, 16 with hyperthreading.

**Comment by Dandandan** [comment]
Might be good to provide an automated way of creating the number of partitions based on a heuristic on startup if the configuration is not set like DataFusion does?
E.g. `SUM(core_count)`.

**Comment by andygrove** [comment]
> Might be good to provide an automated way of creating the number of partitions based on a heuristic on startup if the configuration is not set like DataFusion does? E.g. `SUM(core_count)`.

This is challenging because it is the scheduler process that needs to use this setting, and it has no way today of knowing how many cores are in the cluster AFAIK. The scheduler may start up before any executors as well.

Eventually, I would expect us to dynamically re-partition and coalesce partitions in a similar way to Spark AQE, based on the size and number of partitions coming out of each query stage.

**Comment by andygrove** [comment]
> IMO 2 is clearly not a good choice for multi-core machines in 2022. 16 sounds much more practice in an age where the lowest core count will likely be 8, 16 with hyperthreading.

Thanks for the sanity check on this arbitrary number that I picked. For reference, Spark's default is 200. I didn't want to go that far, at least for now.

**Comment by avantgardnerio** [comment]
I agree with this comment:

```
message ExecutorResource {
  // TODO add more resources
  oneof resource {
    uint32 task_slots = 1;
  }
}
```

Maybe @yahoNanJing has some input? Do you have more advanced resource reporting on your fork?

**Comment by yahoNanJing** [comment]
Hi @avantgardnerio, actually at our side, we set the partition number depending on different kinds of tables at the client side. In the future, we can adjust the number based on some stats. However, currently it's better to enlarge it from 2 to 16

**Pull request merged**
