### PR TITLE
Issue 162 build docker image in ci

### LINKED ISSUE #162: Build Docker images in CI
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I tried to build the docker images using the instructions in the user guide, and it failed because we are using an old Rust version.

**Describe the solution you'd like**
Add CI workflow to build docker images so we don't break this again.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by paolorechia**
# Which issue does this PR close?

Closes #162

 # Rationale for this change
Prevent stale/broken builds in the main branch.

# What changes are included in this PR?
New CI workflow that runs the `./dev/build-ballista-docker.sh` script on Pull Request trigger.

# Are there any user-facing changes?
No

Example run: https://github.com/paolorechia/arrow-ballista/actions/runs/4517673072/jobs/7957036021#step:3:2264

### CODE REVIEW

**Comment by paolorechia** [comment]
As ran into issues during the build process, I opened another PR to enable the docker build with the bash script.

**Comment by paolorechia** [comment]
This seems to be working (https://github.com/paolorechia/arrow-ballista/actions/runs/4518250344), but depends on merging first the PR: https://github.com/apache/arrow-ballista/pull/718

**Comment by xin-hao-awx** [comment]
This PR is very useful for the guys who want to give a try the Ballista with K8s.
@andygrove can you have a look?

**Comment by paolorechia** [comment]
@avantgardnerio thanks for the review!
I think another PR was merged to fix the docker build, would you be able to re-run the build pipeline and see if it passes now?

**Comment by paolorechia** [comment]
@avantgardnerio it seems like merged it:

https://github.com/apache/arrow-ballista/pull/794

Is it still broken? Should I fix the merge conflicts so we can try with the NVM build?

**Comment by avantgardnerio** [comment]
> Is it still broken?

For whatever reason, github is not giving me the ability to trigger this build. I'd suggest rebasing it onto main if that hasn't been done already or pushing an empty commit.

**Comment by paolorechia** [comment]
@avantgardnerio sorry, I forgot to update the branch. I did it now and it seems to pass.

**Review by avantgardnerio — APPROVED** [review]

**Pull request merged**
