### PR TITLE
Filter field for `JoinNode` and  `HashJoinExecNode`

### PR DESCRIPTION
**Pull request by korowa**
# Which issue does this PR close?

Related issue: https://github.com/apache/arrow-datafusion/issues/2496

Should be merged after https://github.com/apache/arrow-datafusion/pull/2591

 # Rationale for this change

Support JoinFilter in Ballista serde code

# What changes are included in this PR?

JoinFilter structure added to logical and physical plan .proto and serialization/deserialization methods

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/issues/2496 is merged

**Comment by korowa** [comment]
All tests passed with new revision from apache/datafusion repo

**Comment by korowa** [comment]
@andygrove, could you, please, take a look, when you have time?

**Review by andygrove — APPROVED** [review]
Thanks @korowa

**Pull request merged**
