### PR TITLE
bump datafusion version

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

Upgrade to latest DataFusion (we're releasing a new version in the next few days)

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by andygrove** [comment]
@yahoNanJing @thinkharderdev @avantgardnerio PTAL when you can

**Comment by yahoNanJing** [comment]
Thanks @andygrove. All looks good except there's some checks failed.

**Review by yahoNanJing — APPROVED** [review]

**Comment by avantgardnerio** [comment]
This looks like it bumps Ballista to point at `312a7dd3b9642e64555bd0cfa90f4e10145ea103` which is a commit from 2022-08-31 (just after the arrow 21 upgrade)?

I have a fork of Ballista working against a newer Datafusion and arrow-rs 22. If we're going for it, I'd love to see us go all the way.

**Comment by andygrove** [comment]
> This looks like it bumps Ballista to point at `312a7dd3b9642e64555bd0cfa90f4e10145ea103` which is a commit from 2022-08-31 (just after the arrow 21 upgrade)?
> 
> I have a fork of Ballista working against a newer Datafusion and arrow-rs 22. If we're going for it, I'd love to see us go all the way.

I also have https://github.com/apache/arrow-ballista/pull/200 open, which brings us up to DataFusion as of yesterday (2022-09-10).

**Comment by andygrove** [comment]
This PR uses DataFusion 8b59b207aaadd6f2c19c28d1f1431a0cb8d110ae which already uses Arrow 22

**Pull request merged**
