### PR TITLE
Use latest DataFusion

### LINKED ISSUE #84: Upgrade dependency of arrow-datafusion to commit d0d5564b8f689a01e542b8c1df829d74d0fab2b0
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Recently there are many improvements and bug fixes in arrow-datafusion, especially the object store interface refactoring https://github.com/apache/arrow-datafusion/pull/2677. It's better for us to upgrade this dependency. By the commit d0d5564b8f689a01e542b8c1df829d74d0fab2b0, the arrow will be upgraded to 18.0.0

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #84.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
Hi @alamb and @andygrove, could you help review this PR?

**Comment by andygrove** [comment]
I tried running the integration tests from this branch, by running `./dev/integration-tests.sh`, and they failed with:

```
error: failed to select a version for the requirement `parquet = "^18.0.0"`
candidate versions found which didn't match: 15.0.0, 14.0.0, 13.0.0, ...
```

**Comment by yahoNanJing** [comment]
Thanks @andygrove. I didn't run the test. I'll fix it.

**Review by andygrove — APPROVED** [review]
LGTM. I had to update the ballista-base dockerfile to use a newer Rust version and then the integration tests ran:

```
FROM rust:1.62.0-buster AS builder
```

I don't really understand why this helped though.

**Comment by yahoNanJing** [comment]
The rust version on my Mac is also 1.62.0. Maybe we need to update the rust version in the toml as well later. By the way, really appreciate the docker-based integration tests.

**Comment by andygrove** [comment]
I will merge in the next couple days if there is no more feedback. 

@thinkharderdev @Ted-Jiang - do you want to review?

**Review by thinkharderdev — APPROVED** [review]
LGTM

**Review by alamb — COMMENTED** [review]
epic work @yahoNanJing  ❤️ It is cool to see the net deletion of code

**Review by Ted-Jiang — COMMENTED** [review]
👍👍👍

**Pull request merged**
