### PR TITLE
Use a vector to indicate the output links for ExecutionStage

### LINKED ISSUE #144: A stage may act as the input of multiple stages
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A stage may act as the input of multiple stages.

**Describe the solution you'd like**

We should use a vector to indicate the output links for *ExecutionStage*.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #144.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
Hi @thinkharderdev, could you help review this PR?

**Comment by yahoNanJing** [comment]
Hi @andygrove, could you help review this PR?

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @yahoNanJing. It is nice to see the proto code moving to a more appropriate place.

**Comment by yahoNanJing** [comment]
We can close this, since it's already been merged to the main branch.

**Pull request closed without merging**
