### PR TITLE
Bump DataFusion

### PR DESCRIPTION
**Pull request by Dandandan**
# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Dandandan** [comment]
Some failures with column indices. Will have a look later

**Review by andygrove — APPROVED** [review]

**Comment by Dandandan** [comment]
@andygrove there is some error wrt schema handling

**Comment by Dandandan** [comment]
Seems to have to do with `HashBuildProbeOrder` and I guess the introduced LeftSemi/RightSemi support :thinking:

**Comment by Dandandan** [comment]
I have a PR open in DataFusion that probably would fix t he is, but need to add some tests there

**Comment by Dandandan** [comment]
https://github.com/apache/arrow-datafusion/pull/4000

**Comment by Dandandan** [comment]
No problems anymore.

We can see it now switches to the right semi join in q18 (20% improvement on my machine):

```
      HashJoinExec: mode=Partitioned, join_type=RightSemi, on=[(Column { name: "l_orderkey", index: 0 }, Column { name: "o_orderkey", index: 2 })], metrics=[output_rows=4368, input_rows=59985993, input_batches=3550, output_batches=3550, join_time=1.121241193s]
```

Before:

```
      HashJoinExec: mode=Partitioned, join_type=Semi, on=[(Column { name: "o_orderkey", index: 2 }, Column { name: "l_orderkey", index: 0 })], metrics=[output_rows=4368, input_batches=32, output_batches=32, input_rows=4992, join_time=150.113398ms]
```


Also q20 has a ~10% improvement compared to master.

The HashJoinExec don't report the full metrics the `join_time` doesn't include building the hashmap, which is the more expensive part of joins, Also setting the bitmap isn't currently included in `join_time`.

**Comment by Dandandan** [comment]
Also q4 got a bit faster - this change is doing better than expected!

**Pull request merged**
