### PR TITLE
Update datafusion dependency to the latest version

### LINKED ISSUE #610: Update latest datafusion dependency
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

#603

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #610, #603.

 # Rationale for this change

# What changes are included in this PR?

Since the physical plan part has already been moved from Ballista to the Datafusion, the related code in Ballista also needs to be cleaned up. What's more, the Ballista specific Execution Plan, like `ShuffleReaderExec`, `ShuffleWriterExec`, `UnresolvedShuffleExec` need to be reimplemented with leveraging the `PhysicalExtensionCodec`.

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
This PR will be refined after the Datafusion publish a new minor version

**Comment by andygrove** [comment]
DataFusion 16.1.0 has now been released

**Comment by andygrove** [comment]
@yahoNanJing You may need to update to latest rust to have same clippy rules as CI

**Comment by andygrove** [comment]
@avantgardnerio fyi

**Review by andygrove — APPROVED** [review]

**Pull request merged**
