### PR TITLE
Upgrade DataFusion to 27.0.0

### PR DESCRIPTION
**Pull request by r4ntix**
# Which issue does this PR close?

Upgrade:
* DataFusion to 27.0.0
* ObjectStore to 0.6.1
* SqlParser to 0.35.0

# Rationale for this change

# What changes are included in this PR?

Upgrade:
* DataFusion to 27.0.0
* ObjectStore to 0.6.1
* SqlParser to 0.35.0

# Are there any user-facing changes?

None

### CODE REVIEW

**Comment by r4ntix** [comment]
Relate Issue: https://github.com/apache/arrow-datafusion/issues/6819

**Comment by r4ntix** [comment]
Related Issue: https://github.com/apache/arrow-datafusion/issues/6898

**Comment by r4ntix** [comment]
@yahoNanJing if you have time, could you help review it?

**Review by yahoNanJing — APPROVED** [review]
LGTM

**Pull request merged**
