### PR TITLE
Bump DataFusion version

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

N/A

 # Rationale for this change

I would like to test some of the bug fixes in DF and see if more of the benchmark queries now work.

# What changes are included in this PR?

Use DF just before https://github.com/apache/arrow-datafusion/pull/3907 because we are talking about rolling that back.

# Are there any user-facing changes?

I don't know yet

### CODE REVIEW

**Comment by Dandandan** [comment]
Looks great - I went ahead and fixed the cargo.toml bug - this uncovered some necessary changes needed in the python crate.

I believe the other test is https://github.com/apache/arrow-datafusion/pull/3953

**Comment by Dandandan** [comment]
This brings also some improvements to q7 and q19 :partying_face:

**Comment by yahoNanJing** [comment]
Looks great. One more thing about the format of the datafusion.proto, is there any standard format so that future PRs will not be influenced by the format change?

**Comment by Dandandan** [comment]
I also pushed changes to compile python and updated revs.
Let's see if everything is green now.

**Comment by Dandandan** [comment]
The earlier failing test passes now too

**Comment by andygrove** [comment]
Thanks @Dandandan !

**Comment by andygrove** [comment]
> Looks great. One more thing about the format of the datafusion.proto, is there any standard format so that future PRs will not be influenced by the format change?

Filed https://github.com/apache/arrow-ballista/issues/462 for this

**Comment by andygrove** [comment]
LGTM. I cannot approve because I created the PR.

**Review by yahoNanJing — APPROVED** [review]

**Pull request merged**
