### PR TITLE
Update task status to the its job curator scheduler

### LINKED ISSUE #179: Update task status to the task job curator scheduler
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

By introducing #130, we need to refine the task update for the executor by sending rpc to the task job curator scheduler.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by yahoNanJing**
# Which issue does this PR close?

Closes #179.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by yahoNanJing** [comment]
Hi @thinkharderdev, @andygrove, @avantgardnerio, could you help have a review?

Later I will propose another PR for dealing with multiple schedulers registration and heartbeating.

**Comment by avantgardnerio** [comment]
I will review in more depth tomorrow, but my main question with this series of PRs is: does Ballista remain releasable/functional as they are merged? Or do they all need to land before the new single-curator architecture is ready for action?

**Comment by yahoNanJing** [comment]
Hi @avantgardnerio, thanks for your comment. Yes, this PR will not break the ballista function.

**Comment by avantgardnerio** [comment]
@alamb might be able to help with reviews as well.

**Review by thinkharderdev — APPROVED** [review]
Great work!

**Comment by andygrove** [comment]
@yahoNanJing This one needs a rebase now

**Comment by alamb** [comment]
>  @alamb might be able to help with reviews as well.

FYI to avoid miscommunication, I am unlikely to have time to review ballista PRs -- my open source time is already (more than) occuplied with sqlparser, arrow-rs and datafusion ;) 

I am happy to help with logistical support but I just don't want you all to labor under bad expectations

**Comment by alamb** [comment]
> I am happy to help with logistical support but I just don't want you all to labor under bad expectations

I should also point out that we encourage everyone to help with reviews (not just committers) -- I think especially as @yahoNanJing  and the rest of the Ebay team become more experts in Ballista you are likely well positioned to take on a leading role with reviews.

**Comment by yahoNanJing** [comment]
Hi @andygrove, just rebased.

**Comment by avantgardnerio** [comment]
> Hi @alamb, we are willing to lead the ballista to be a better product for production usage. Recently we are working on several things, like performance enhancement, error handling, etc.
> 
> Thanks @thinkharderdev and @avantgardnerio for engaging reviewing on bunch of PRs recently from us. It would be much better to have more people from different background engaging on ballista things, like issue proposing, PR reviewing, etc smile

We're very happy to @yahoNanJing . I appologize for not yet having enough context on some of these more architectural PRs at this point in time, but I've requested our (S&T) engineers focus more on Ballista than DataFusion to compensate for the disproportionate amount of reviewers on the two projects.

Our company is committed to Ballista, we have 3.5 engineers on it at present, and I'm sure that number will go up. As it does and we gain experience, we look forward to working with you!

**Review by avantgardnerio — APPROVED** [review]

**Comment by alamb** [comment]
It is very exciting to see the acceleration of people engaging and contributing to the Ballista project ❤️

**Comment by alamb** [comment]
Since this has two approvals, merging it in. I will also attempt to get some more committer bandwidth for Ballista. Stay tuned

**Pull request merged**
