### PR TITLE
Add GCS and Azure support

### LINKED ISSUE #294: Add support for Azure blob storage
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Add support for querying data in Azure blob storage.

**Describe the solution you'd like**
Follow the pattern in https://github.com/apache/arrow-ballista/pull/290

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by onthebridgetonowhere**
# Which issue does this PR close?

Closes #294 and #293.

 # Rationale for this change
Adds support for Azure & GCS

# What changes are included in this PR?
Just what's required for supporting Azure & GCS

# Are there any user-facing changes?
No

### CODE REVIEW

**Comment by andygrove** [comment]
@onthebridgetonowhere This all looks reasonable. Were you able to test this to make sure it works?

**Comment by onthebridgetonowhere** [comment]
@andygrove good point. Unfortunately, I do not have the possibility of testing these. I'd have to look into how to test these as I don't have access/accounts to them. If you have, feel free to try them.

**Comment by andygrove** [comment]
Moving this to draft for now

**Comment by andygrove** [comment]
It looks like progress is stalled here, so I am going to go ahead and close this. We can re-open if anyone wants to pick this up.

**Pull request closed without merging**
