### PR TITLE
Use local shuffle reader in containerized environments and some impro…

### LINKED ISSUE #356: Use local shuffle reader in containerized environments
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
https://github.com/apache/arrow-ballista/pull/347 adds a local shuffle reader. It uses the shuffle read URL to determine if a fetch is local or not. This works well when running as standalone processes but does not work so well in a containerized environment such as k8s where multiple executors could be running on the same host but in different containers.

**Describe the solution you'd like**
Why don't we just look on disk to see if the shuffle files exist locally

**Describe alternatives you've considered**
None

**Additional context**
See discussion at https://github.com/apache/arrow-ballista/pull/347#discussion_r995794572

### PR DESCRIPTION
**Pull request by Ted-Jiang**
…vements.

# Which issue does this PR close?

Closes #356.

 # Rationale for this change

1. support containerized environments
2. Modify Error type for scheduler retry task
3. Make local shuffle files read serially for better memory control

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@andygrove  @yahoNanJing  @mingmwang  Test with tpch-1g query1 in local mac, no error no performance downgrade.

**Review by Ted-Jiang — COMMENTED** [review]
@andygrove  @yahoNanJing  @mingmwang  Test with tpch-1g query1 in local mac, no error no performance downgrade.

**Review by andygrove — APPROVED** [review]
Thanks @Ted-Jiang! I don't have an environment to fully test this but I ran this with docker compose and saw no regressions in performance

**Review by yahoNanJing — COMMENTED** [review]
LGTM

**Pull request merged**
