### PR TITLE
Delegate to `datafusion-proto` for logical plan serde

### PR DESCRIPTION
**Pull request by andygrove**
# Which issue does this PR close?

Part of https://github.com/apache/arrow-ballista/issues/2

 # Rationale for this change

Remove duplicate code from this project and delegate to DataFusion instead.

# What changes are included in this PR?

- Remove `AsLogicalPlan`, `LogicalExtensionCodec` and use the versions from `datafusion-proto`
- Removes more than 1,000 lines of code here

# Are there any user-facing changes?

No

### CODE REVIEW

**Comment by andygrove** [comment]
@thinkharderdev This is a new PR for delegating to datafusion-proto and now it just uses the `AsLogicalPlan` trait from that crate

**Review by alamb — APPROVED** [review]
Looks good to me, though I think @thinkharderdev  should also weigh in

**Review by thinkharderdev — APPROVED** [review]
Looks great!

**Comment by alamb** [comment]
bird-parrot

**Pull request merged**
